### PR TITLE
Add defaultValue variable

### LINKED ISSUE #66: Add variable for `rememberPrevious` value
I would like to be able to pass the value from `rememberPrevious` (the default value) to the command.

Basically, I want to do:
```json
"command": "echo ${defaultValue}"
```

The reason I want to do this is a hack so that an input in `launch.json` can be used in `tasks.json` for a `preLaunchTask`. VSCode does not offer a way to do this as far as I know. In `launch.json`, I would have the real command, and in `tasks.json` I would have `"echo ${defaultValue}"` with the same `taskId` and `useFirstResult` set to true. Maybe there is a better way, but I can't find any way to do this.

### PR DESCRIPTION
**Pull request by MarcelRobitaille**
Fixes #66 

Add a variable `defaultValue` for the last used value when `rememberPrevious` is true.

### CODE REVIEW

**Comment by augustocdias** [comment]
I'd suggest to rename the variable name. It is not default its the value from the last pick. Perhaps `rememberedValue`?

**Comment by augustocdias** [comment]
There are conflicts. I can't merge it

**Comment by MarcelRobitaille** [comment]
@augustocdias Really? It's green for me. 
image

I just tried to merge master into my branch locally and it said `Everything up-to-date`

**Comment by augustocdias** [comment]
Hey... Things have been hectic at home and it can take a while until I can take a look on this... Please be patient and thanks for understanding

**Pull request merged**
