### PR TITLE
Add line number variable

### PR DESCRIPTION
**Pull request by MarcelRobitaille**
Add the variable `lineNumber`, which is consistent with [the build in VSCode variables](https://code.visualstudio.com/docs/editor/variables-reference).

### CODE REVIEW

**Comment by bauersimon** [comment]
Is this PR going to be part of a new release soon? The latest release is 1.8.2 from March 2023 and doesn't yet contain this. Would love to use it.

**Comment by augustocdias** [comment]
Hey... Things have been hectic at home and it can take a while until I can take a look on this... Please be patient and thanks for understanding...

I haven't released because I didn't have time to test and since my knowledge of typescript and vscode's extension dev is quite limited I didn't have time to implement proper tests...

**Comment by MarcelRobitaille** [comment]
Hi augustocdias. I totally understand. Until you have a bit more time, would you object to my publishing my fork as it's own extension? I can also have a look at some of the open issues here.

**Comment by augustocdias** [comment]
> Hi augustocdias. I totally understand. Until you have a bit more time, would you object to my publishing my fork as it's own extension? I can also have a look at some of the open issues here.

No worries... You can always install from a pre built vsix package as well.

**Comment by MarcelRobitaille** [comment]
I published my fork here: https://marketplace.visualstudio.com/items?itemName=marcelrobitaille.tasks-shell-input-ngx. If you don't want this fork to exist, please let me know at any time.

@bauersimon 1.8.3 published there already has this `lineNumber` variable.

**Comment by augustocdias** [comment]
I don't mind. If you're willing to put some work on it I can add you as a maintainer.

**Comment by MarcelRobitaille** [comment]
@augustocdias yes that would also work. I'm honored that you trust me enough to make me a maintainer. Shall I merge in those changes and archive the fork?

**Comment by augustocdias** [comment]
Yeah. Lets do that. I'll add you as a maintainer of the project.

**Comment by MarcelRobitaille** [comment]
Thank you very much for doing that. How does publishing work? I assume you're still the only one who can do that.

I hope you never feel any rush to reply to me. Take as much time as you need.

**Comment by augustocdias** [comment]
No worries. Publishing consists in just creating a new release/tag. I usually create it through GitHub's UI. 

Just remember, before creating the tag, to push a commit with the new version number in the package.json and update the changelog with the new features and bug fixes. Here's an example commit:

https://github.com/augustocdias/vscode-shell-command/commit/3f3601cbb9de8dda396b04a4987a889b6cf707e5

**Comment by MarcelRobitaille** [comment]
Oh cool I didn't know you could do it just with tags. I thought I had to do `vsce publish` and somehow get an authentication token to your microsoft account. Tags is much easier.

**Comment by mkiessling-ifx** [comment]
Hi, I thank you so much for your contributions!

@MarcelRobitaille: Can you please tell the status, if your VSCode extension "Task Shell Input ngx" is needed and up-to-date? 
If so and merged with "Task Shell Input" is is possible to remove the "ngx" extension from VS Code Marketplace? 

Thank you! :-)

**Comment by MarcelRobitaille** [comment]
@mkiessling-ifx My extension is deprecated. I made a request to have it marked as deprecated in VSCode quite some time ago, but I guess it hasn't gone through yet. 

https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-10741912

**Comment by mkiessling-ifx** [comment]
@MarcelRobitaille : I haven't noticed any hint about deprecation in the description or change log. Anyhow, Thank you for your contribution and fast response again!

**Comment by MarcelRobitaille** [comment]
@mkiessling-ifx updated the readme and archived the repo

**Pull request merged**
